config/routes.rb
Rails.application.routes.draw do

  resources :activity_lists
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' } 
  resources :activities do
  
    get :only_user, on: :collection, as: :only_user
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #custom routes 
  get 'about-me', to: 'pages#about'
  #get 'contact', to: 'contact_us/contacts#new'
  root to: 'pages#home'
end

app/models/activity_list.rb
class ActivityList < ApplicationRecord
  has_many :activities
end

app/controllers/activity_lists_controller.rb
class ActivityListsController < ApplicationController
  before_action :set_activity_list, only: [:show, :edit, :update, :destroy]

  # GET /activity_lists
  # GET /activity_lists.json
  def index
    @activity_lists = ActivityList.all
  end

  # GET /activity_lists/1
  # GET /activity_lists/1.json
  def show
  end

  # GET /activity_lists/new
  def new
    @activity_list = ActivityList.new
  end

  # GET /activity_lists/1/edit
  def edit
  end

  # POST /activity_lists
  # POST /activity_lists.json
  def create
    @activity_list = ActivityList.new(activity_list_params)

    respond_to do |format|
      if @activity_list.save & current_user.admin?
        format.html { redirect_to @activity_list, notice: 'Activity list was successfully created.' }
        format.json { render :show, status: :created, location: @activity_list }
      else
        format.html { render :new }
        format.json { render json: @activity_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_lists/1
  # PATCH/PUT /activity_lists/1.json
  def update
    respond_to do |format|
      if @activity_list.update(activity_list_params) & current_user.admin?
        format.html { redirect_to @activity_list, notice: 'Activity list was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity_list }
      else
        format.html { render :edit }
        format.json { render json: @activity_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_lists/1
  # DELETE /activity_lists/1.json
  def destroy
    @activity_list.destroy
    respond_to do |format|
      format.html { redirect_to activity_lists_url, notice: 'Activity list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_list
      @activity_list = ActivityList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_list_params
      params.require(:activity_list).permit(:name, :theme, :main_image, :thumb_image)
    end
end

app/helpers/activity_lists_helper.rb
module ActivityListsHelper
end

app/views/activity_lists/_form.html.erb
<% if current_user.try(:admin?) %>

    <%= bootstrap_form_for(activity_list) do |form| %>
        <% if activity_list.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(activity_list.errors.count, "error") %> prohibited this activity_list from being saved:</h2>

                <ul>
                    <% activity_list.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <%= form.text_field :name, id: :activity_list_name %>
        <%= form.text_field :theme, id: :activity_list_theme %>
        <%= form.text_field :main_image, id: :activity_list_main_image %>
        <%= form.text_field :thumb_image, id: :activity_list_thumb_image %>
        <%= form.submit %>
    <% end %>
<% else %>
    You don't have administrator rights. 
    <br>

<% end %>

app/views/activity_lists/edit.html.erb
<h1 class="inline">Editing Activity List</h1>
<%= link_to 'Back', activity_lists_path, class: "btn btn-light float-right" %>
<%= link_to 'Show', @activity_list, class: "btn btn-info float-right" %> 

<%= render 'form', activity_list: @activity_list %>

app/views/activity_lists/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <h1 class="inline">Activity Lists</h1>
    <% if current_user.admin %>
        <%= link_to 'New Activity', new_activity_list_path, class: "btn btn-success float-right" %>
    <% end %>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Name</th>
                <th scope="col">Theme</th>
                <th scope="col">Main image</th>
                <th scope="col">Thumb image</th>
                <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% @activity_lists.each_with_index do |activity_list, idx| %>
                <tr>
                    <td><%= idx + 1 %></td>
                    <td><%= activity_list.name %></td>
                    <td><%= activity_list.theme %></td>
                    <td><%= activity_list.main_image %></td>
                    <td><%= activity_list.thumb_image %></td>
                    <td>
                        <div class="btn-group btn-group-sm">
                            <%= link_to 'Show', activity_list, class: "btn btn-info" %>
                            <% if current_user.try(:admin?) %>
                                <%= link_to 'Edit', edit_activity_list_path(activity_list) , class: "btn btn-warning"  %>
                                <%= link_to 'Destroy', activity_list, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>

app/views/activity_lists/new.html.erb
<h1 class="inline">New Activity List</h1>
<%= link_to 'Back', activity_lists_path, class: "btn btn-light float-right" %>

<%= render 'form', activity_list: @activity_list %>

app/views/activity_lists/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col-md">
        <div class="card bg-dark border-primary mx-auto mb-3" style="width: 18rem;">
            <div class="card-header">
                <strong>Name:</strong>
                <%= @activity_list.name %>
            </div>

            <ul class="list-group list-group-flush list-group-item-dark">
                <li class="list-group-item list-group-item-dark">
                    <strong>Theme:</strong>
                    <%= @activity_list.theme %>
                    <%= image_tag @activity_list.thumb_image %>
                </li>
                <li class="list-group-item list-group-item-dark">
                    <% if current_user.try(:admin?) %>
                        <%= link_to 'Edit', edit_activity_list_path(@activity_list), class: "btn btn-warning" %> 
                    <% end %>
                    <%= link_to 'Back', activity_lists_path, class: "btn btn-light float-right" %>
                </li>
            </ul>
        </div>

    </div> 
    <div class="col-md">
        <div class="card bg-dark mx-auto">
            <%= image_tag @activity_list.main_image, class: "mx-auto" %>
        </div> 
    </div> 
</div>