config/routes.rb
Rails.application.routes.draw do

  resources :activity_lists
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' } 
  resources :activities do
  
    get :only_user, on: :collection, as: :only_user
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #custom routes 
  get 'about-me', to: 'pages#about'
  #get 'contact', to: 'contact_us/contacts#new'
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<!-- Footer -->
<footer class="pt-2 footer">
    <div class="container">
        <div class="row">

            <div class="col-md-6 mb-1 mx-auto">
                <h3>Links</h3>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <%= link_to "Home", root_path, class: "" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "About", about_me_path, class: "" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Contact", contact_us_path, class: "" %>
                    </li>
                </ul>
            </div>
            <div class="col-md-6 mb-1 mx-auto">
                <h3>Created by</h3>
                <div class="text-secondary">
                    Daniel Kukula
                    All Rights reserved
                    2017-2018<br>
                    Graphics kindly provided by Roksana Godzierz<br>
                    Homepage background video by <a href="https://m.youtube.com/channel/UCJFoMrK06Be-kFaQAo52dmQ">HowardFreeman Motivation</a>
                </div>
            </div>    
        </div>
    </div>
</footer>

app/views/shared/_application_nav.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" id="mainNav">
    <%= link_to "Move & Groove", root_path, class: "nav-link navbar-brand" %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon custom-toggler"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to "Activities", activities_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "About", about_me_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Contact", contact_us_path, class: "nav-link" %>
            </li>
            <% if current_user.try(:admin?) %>
                <li>
                    <%= link_to "Activities List", activity_lists_path, class: "nav-link" %>
                </li>
            <% end %>
        </ul>
        <ul class="nav navbar-nav">
            <% if current_user %>
                <li class="nav-item">
                    <%= link_to "Hello #{current_user.name}", edit_user_registration_path, class: "nav-link" %>

                </li>
                <li class="nav-item">
                    <%= link_to "Logout", destroy_user_session_path, class: "nav-link", method: :delete %>

                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to "Register", new_user_registration_path, class: "nav-link"  %>
                </li>
                <li class="nav-item">
                    <%= link_to "Login", new_user_session_path, class: "nav-link"  %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>