config/routes.rb
Rails.application.routes.draw do

  resources :activity_lists
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' } 
  resources :activities do
  
    get :only_user, on: :collection, as: :only_user
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #custom routes 
  get 'about-me', to: 'pages#about'
  #get 'contact', to: 'contact_us/contacts#new'
  root to: 'pages#home'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :activity_list
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :get_activity_list
  before_action :get_users, only: [:index, :only_user]
  # GET /activities
  # GET /activities.json
  def index
      @activities = Activity.order("date desc")
      if current_user
        @activities_user = Activity.where(user_id: current_user.id).order("date desc")
      end
    #.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        byebug
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def only_user
        @activities_user = Activity.where(user_id: current_user.id).order("date desc")
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    def get_activity_list
      @activity_list = ActivityList.all
    end
    def get_users
      @users = User.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:activity_list_id, :date, :duration, :kcal, :user_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<% if current_user %>
    <%= bootstrap_form_for(activity) do |form| %>
        <% if activity.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

                <ul>
                    <% activity.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        <%= form.select(:activity_list_id, options_from_collection_for_select(@activity_list, :id, :name), { :class => "form-control" }) %>
        <%= form.date_select :date, id: :activity_date, class: "form-control datepicker" %>
        <%= form.number_field :duration, id: :activity_duration, class: "form-control" %>
        <%= form.number_field :kcal, id: :activity_kcal, class: "form-control" %>
        <%= form.hidden_field :user_id, value: current_user.id %>

        <div class="actions">
            <%= form.submit %>
        </div>
    <% end %>

</div> 

<% else %>
    <p class="text-warning">
        You need to be logged in to add activities
    </p>
<% end %>

app/views/activities/edit.html.erb
<h1 class="inline">Editing Activity</h1>
<%= link_to 'Back', activities_path, class: "btn btn-light float-right" %>
<%= link_to 'Show', @activity, class: "btn btn-info float-right" %>

<%= render 'form', activity: @activity %>

app/views/activities/index-user.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <h1 class="inline">Activities</h1>
    <%= link_to 'New Activity', new_activity_path, class: "button float-right" %>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Date</th>
                <th scope="col">Type</th>
                <th scope="col">Duration</th>
                <th scope="col">Kalories</th>
                <th scope="col"> </th>
            </tr>
        </thead>

        <tbody>
            <% @activities.each_with_index do |activity, idx| %>
                <tr>
                    <th scope="row"><%= idx + 1 %></th>
                    <td><%= activity.date %></td>
                    <td><%= image_tag @activity_list.find(activity.activity_list_id).thumb_image unless @activity_list.find(activity.activity_list_id).thumb_image.nil?  %>  <%= @activity_list.find(activity.activity_list_id).name %></td>
                    <td><%= activity.duration %> min</td>
                    <td><%= activity.kcal %> kcal</td>
                    <td>
                        <div class="btn-group btn-group-sm">
                            <%= link_to 'Show', activity, class: "btn btn-info" %>
                            <% if current_user && current_user.id == activity.user_id %>
                                <%= link_to 'Edit', edit_activity_path(activity), class: "btn btn-warning" %>
                                <%= link_to 'Destroy', activity, class: "btn btn-danger",  method: :delete, data: { confirm: 'Are you sure?' } %>
                            <% end %>
                        </div>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <br>
</div>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <h1 class="inline">Activities</h1>
    <%if current_user %>
        <%= link_to 'New Activity', new_activity_path, class: "btn btn-success float-right" %>
        <%= link_to "I'm anti social", only_user_activities_path, class: "btn btn-light float-right" %>
    <% end %>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Date</th>
                <th scope="col">User</th>
                <th scope="col">Type</th>
                <th scope="col">Duration</th>
                <th scope="col">Kalories</th>
                <th scope="col"> </th>
            </tr>
        </thead>

        <tbody>
            <% activities_to_display = @activities %>

            <% activities_to_display.each_with_index do |activity, idx| %>
                <tr>
                    <th scope="row"><%= idx + 1 %></th>
                    <td><%= activity.date %></td>
                    <td>
                        <%= if @users.where(:id => activity.user_id).blank?
                                "user hidden"
                            else
                                @users.find(activity.user_id).name
                            end %>
                        </td>
                        <td>
                            <% if @activity_list.where(:id => activity.activity_list_id).blank? %>
                                <%= "unknown activity"%>
                            <%  else %>
                                <%= image_tag @activity_list.find(activity.activity_list_id).thumb_image unless @activity_list.find(activity.activity_list_id).thumb_image.nil? %>
                                <%= @activity_list.find(activity.activity_list_id).name %>
                            <%  end %>
                        </td>
                        <td><%= activity.duration %> min</td>
                        <td><%= activity.kcal %> kcal</td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <%= link_to 'Show', activity, class: "btn btn-info" %>
                                <% if current_user && current_user.id == activity.user_id %>
                                    <%= link_to 'Edit', edit_activity_path(activity), class: "btn btn-warning" %>
                                    <%= link_to 'Destroy', activity, class: "btn btn-danger",  method: :delete, data: { confirm: 'Are you sure?' } %>
                                <% end %>
                            </div>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>

app/views/activities/new.html.erb
<h1 class="inline">New Activity</h1>
<%= link_to 'Back', activities_path, class: "btn btn-light float-right"%>
<%= render 'form', activity: @activity %>

app/views/activities/only_user.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <h1 class="inline">Activities</h1>
    <%= link_to 'New Activity', new_activity_path, class: "btn btn-success float-right" %>
    <%= link_to "I'm social", activities_path, class: "btn btn-light float-right" %>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Date</th>
                <th scope="col">User</th>
                <th scope="col">Type</th>
                <th scope="col">Duration</th>
                <th scope="col">Kalories</th>
                <th scope="col"> </th>
            </tr>
        </thead>

        <tbody>

            <% activities_to_display = @activities_user %>
            <% activities_to_display.each_with_index do |activity, idx| %>
                <tr>
                    <th scope="row"><%= idx + 1 %></th>
                    <td><%= activity.date %></td>
                    <td><%= @users.find(activity.user_id).name %></td>
                    <td>
                        <% if @activity_list.where(:id => activity.activity_list_id).blank? %>
                            <%= "unknown activity"%>
                        <%  else %>
                            <%= image_tag @activity_list.find(activity.activity_list_id).thumb_image unless @activity_list.find(activity.activity_list_id).thumb_image.nil? %>
                            <%= @activity_list.find(activity.activity_list_id).name %>
                        <%  end %>
                    </td>
                    <td><%= activity.duration %> min</td>
                    <td><%= activity.kcal %> kcal</td>
                    <td>
                        <div class="btn-group btn-group-sm">
                            <%= link_to 'Show', activity, class: "btn btn-info" %>
                            <% if current_user && current_user.id == activity.user_id %>
                                <%= link_to 'Edit', edit_activity_path(activity), class: "btn btn-warning" %>
                                <%= link_to 'Destroy', activity, class: "btn btn-danger",  method: :delete, data: { confirm: 'Are you sure?' } %>
                            <% end %>
                        </div>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <br>
</div>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card border-primary mx-auto" style="width: 400px">
    <%= image_tag @activity_list.find(@activity.activity_list_id).main_image, class: "card-img-top" unless @activity_list.find(@activity.activity_list_id).main_image.nil?  %>
    <div class="card-body bg-dark">
        <h5 class="card-title">Workout type</h5>
        <p class="card-text"><%= @activity_list.find(@activity.activity_list_id).name %></p>
        <p>
            Date: <%= @activity.date %>
        </p>

        <p>
            Duration: <%= @activity.duration %>
        </p>

        <p>
            Kcal: <%= @activity.kcal %>
        </p>
        <% if current_user && current_user.id == @activity.user_id %>
            <%= link_to 'Edit', edit_activity_path(@activity), class: "btn btn-secondary" %> 
        <% end %>
        <%= link_to 'Back', activities_path, class: "btn btn-light float-right" %>
    </div>
</div>